### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by adamchainz** [jamescooke/blog#13]
I want to follow you by RSS feed but it's missing from the blag :(

Pelican seems to support it, perhaps it's just not active: http://docs.getpelican.com/en/3.6.3/settings.html#feed-settings

**Comment by jamescooke** [comment]
Thanks Adam - there are a number of items I've got backed up on the blog waiting for my attention, not least this. `https` is top of the list. I'll update here when I get a feed in place.

**Comment by adamchainz** [comment]
![](https://media.giphy.com/media/tkYaChn7aZClW/giphy.gif)

**Comment by jamescooke** [comment]
@adamchainz Does this work for you? http://jamescooke.info/feeds/all.atom.xml

**Comment by adamchainz** [comment]
Perfect!
