### ISSUE TITLE
Links to Makefile in prlint project are 404

### ISSUE THREAD

**Issue by rsyring** [jamescooke/blog#24]
Source: https://jamescooke.info/a-successful-pip-tools-workflow-for-managing-python-package-requirements.html

Thanks for the write up.

**Comment by jamescooke** [comment]
Thanks for spotting this 👍 

There are some other fixes for this post coming from @orangespaceman in #23 which I've not published yet too.

I'm going to change the example Makefile to point at https://github.com/jamescooke/flake8-aaa/blob/master/requirements/Makefile , which I'm just updating.
