### ISSUE TITLE
Kindly requesting feedback on a project implementing the `pip-tools` requirements management workflow

### ISSUE THREAD

**Issue by jimustafa** [jamescooke/blog#35]
Thank you for taking the time to write such a useful [blog post](https://jamescooke.info/a-successful-pip-tools-workflow-for-managing-python-package-requirements.html). The approach you describe has become my go-to method for requirements management. In fact, I have started trying to capture the workflow in a `cookiecutter` template. Of course, it is still a work in progress, and, if you have time, I would appreciate any feedback/contributions you may be able to provide. Please find the repository [here](https://github.com/jimustafa/cookiecutter-pylib-reqm). Thanks again!

**Comment by jamescooke** [comment]
Hey @jimustafa Sorry for being slow.

I'm not a user of Cookiecutter, so I've not been able to try out your template, but the README looks nice 👍🏻 

Feel free to drop a link to https://github.com/jimustafa/cookiecutter-pylib-reqm on #9 - it might help you pick up more users.

**Comment by jimustafa** [comment]
Thank you @jamescooke. Appreciate your suggestion, and will add the link in #9.
